Experiment 1 - 


1. Mix all the paragraphs and split the data to a 80-20 split
2. Build the 3 models listed earlier and compute the confusion matrix for the training and
testing datasets.
3. Discuss how your models perform.

We will try 3 types of models - 
1. BOW model
2. Word embeddings (GLOVE)
3. RNN

In [219]:
import pandas as pd 
import json

with open('C:\\Users\\nikhi\\Earning Calls Transcripts\\final_json_data.json') as f:
    json = json.load(f)
    transcript = pd.DataFrame(json)
transcript.head()

  sentiment                                               text
0  positive  Thank you. Good afternoon, everyone. And welco...
1  positive  As we look past Q1, we expect the channel inve...
2   neutral  And your last question comes from the line of ...
3  negative  On the China gaming weakness, is it the slower...
4  negative  I don't know that we could tear that apart, te...

In [220]:
transcript = transcript.reset_index()
transcript.head()

   index sentiment                                               text
0      0  positive  Thank you. Good afternoon, everyone. And welco...
1      1  positive  As we look past Q1, we expect the channel inve...
2      2   neutral  And your last question comes from the line of ...
3      3  negative  On the China gaming weakness, is it the slower...
4      4  negative  I don't know that we could tear that apart, te...

In [221]:
transcript = transcript.drop('index', axis= 1)
transcript.head()

  sentiment                                               text
0  positive  Thank you. Good afternoon, everyone. And welco...
1  positive  As we look past Q1, we expect the channel inve...
2   neutral  And your last question comes from the line of ...
3  negative  On the China gaming weakness, is it the slower...
4  negative  I don't know that we could tear that apart, te...

In [223]:
transcript['sentiment'].isnull().sum()

0

In [224]:
#transcript['sentiment'][1415] = 'Neutral'
transcript['sentiment'][1415]

'neutral'

# Data Preprocessing

In [225]:
transcript['sentiment'] = transcript['sentiment'].apply(lambda x : x.lower())

In [226]:
len(transcript)

1644

In [227]:
transcript.describe()

       sentiment      text
count       1644      1644
unique         3      1542
top      neutral  Operator
freq         833        28

In [228]:
#Remove all the columns with Neutral Sentiment 
transcript = transcript[transcript['sentiment'] != 'neutral']
transcript.head()

  sentiment                                               text
0  positive  Thank you. Good afternoon, everyone. And welco...
1  positive  As we look past Q1, we expect the channel inve...
3  negative  On the China gaming weakness, is it the slower...
4  negative  I don't know that we could tear that apart, te...
5  positive  Thank you. I'll now turn the call back over to...

In [229]:
len(transcript)

811

In [230]:
transcript.describe()

       sentiment                                               text
count        811                                                811
unique         2                                                811
top     positive  Sure. Thanks for the question. I think it's di...
freq         654                                                  1

In [231]:
transcript.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 811 entries, 0 to 1642
Data columns (total 2 columns):
sentiment    811 non-null object
text         811 non-null object
dtypes: object(2)
memory usage: 19.0+ KB

In [232]:
transcript['text'] = transcript['text'].apply(lambda x : x.lower())
transcript

     sentiment                                               text
0     positive  thank you. good afternoon, everyone. and welco...
1     positive  as we look past q1, we expect the channel inve...
3     negative  on the china gaming weakness, is it the slower...
4     negative  i don't know that we could tear that apart, te...
5     positive  thank you. i'll now turn the call back over to...
6     negative  2018 was a record year but it was a disappoint...
8     positive  in addition, we announced a record of 40 plus ...
9     positive  we're also pleased to see growing momentum in ...
10    positive  pairing dlss with ray tracing can provide comp...
12    negative  in addition, hyperscale and cloud purchases de...
13    positive  for example, we recently announced rapids, our...
15    positive  we have also strengthened our product portfoli...
16    positive  moving to pro visualization, revenue reached $...
17    positive  the webcast will be available for replay until...
18    positive  finally, turning to automotive. q4 revenue was...
20    positive  mercedes-benz has also chosen nvidia for its n...
21    negative  moving to the rest of the p&l and balance shee...
25    positive  i had two questions. first, colette, you talke...
26    positive  when we launched the 2070 and 2080, it was the...
27    positive  and i think that right out of the box, it deli...
31    positive  the slowdown is broad based. we saw it across ...
35    positive  the fundamentals of gaming has not changed, th...
36    positive  if you take the methodology that colette descr...
42    positive  with that, i'd like to turn the call over to c...
46    negative  colette, i appreciate all the data you gave us...
47    positive  i’ll start and i’ll let jen-hsun finish that q...
48    negative  i think your math isn't wrong. the part that y...
50    positive  thanks, simona. as you know we lowered fourth ...
51    negative  we don't see them in high performance computin...
52    positive  we have four new growth drivers, four new ways...
...        ...                                                ...
1592  positive  second, our tax rate for 2018 was 16%. this ra...
1593  negative  now let me turn to the results overall. as dav...
1594  positive  our overall performance in 2018 demonstrates t...
1595  positive  turning to page 6 and our individual segments....
1596  positive  moving to underwriting. market volatility, dec...
1597  positive  our investment banking franchise overall remai...
1598  negative  turning to institutional client services on pa...
1599  positive  the remaining decrease reflected lower results...
1601  negative  first, we successfully increased our wallet sh...
1602  positive  second, we remained focused on leveraging our ...
1603  positive  lastly, we remained focused on continued inves...
1604  positive  moving to page 8. in equities, as it relates t...
1605  positive  for 2018, equities produced net revenues of $7...
1606  positive  moving on to equity investing & lending on pag...
1607  positive  moving on to debt investing & lending on page ...
1608  negative  turning to investment management on page 11. t...
1609  negative  now let me turn to page 12 for expenses. as we...
1610  negative  let me take you through the components of our ...
1613  negative  moving on to taxes. as mentioned earlier, our ...
1614  positive  turning to page 13 on capital. our common equi...
1615  positive  for the full year, we repurchased 13.9 million...
1616  positive  turning to balance sheet and liquidity on page...
1617  positive  before taking questions, a few closing thought...
1618  positive  lastly, the management team is motivated by th...
1628  positive  and together, those five names contributed to ...
1632  positive  so i'll start, glenn, and i'll just comment. o...
1637  positive  stephen, maybe one more, just on the i&l busin...
1639  positive  sure. thanks for the question. i think it's di...
1640  positive  and that has thrown up, as i said in my commen...
1642  negative  okay. and then just as a follow-up. just on th...

[811 rows x 2 columns]

In [233]:
import re

In [87]:
#Removing punctuations

In [234]:
transcript.loc[:,'text']= transcript.loc[:,'text'].apply(lambda x : re.sub('[^a-zA-z0-9\s]','',x))
transcript.loc[:,'text'].head()

0    thank you good afternoon everyone and welcome ...
1    as we look past q1 we expect the channel inven...
3    on the china gaming weakness is it the slower ...
4    i dont know that we could tear that apart teas...
5    thank you ill now turn the call back over to j...
Name: text, dtype: object

In [235]:
transcript['text'] = transcript['text'].apply(lambda x : x.lstrip(' '))
transcript['text'].head()

0    thank you good afternoon everyone and welcome ...
1    as we look past q1 we expect the channel inven...
3    on the china gaming weakness is it the slower ...
4    i dont know that we could tear that apart teas...
5    thank you ill now turn the call back over to j...
Name: text, dtype: object

In [236]:
stopwd = stopwords.words('english')
stopwd

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [237]:
stop = stopwords.words('english')
transcript['text'] = transcript['text'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
transcript['text'].head()

0    thank good afternoon everyone welcome nvidias ...
1    look past q1 expect channel inventory correcti...
3    china gaming weakness slower economic environm...
4    dont know could tear apart tease apart harlan ...
5     thank ill turn call back jenhsun closing remarks
Name: text, dtype: object

In [156]:
#stem = PorterStemmer()
#transcript['text_stem'] = transcript['text'].apply(lambda x :" ".join([stem.stem(word) for word in x.split()]))

In [212]:
#transcript['text_stem']

In [238]:
import nltk 
#nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lem = WordNetLemmatizer()

In [239]:
lem.lemmatize('continued',pos='v')

'continue'

In [240]:

transcript['text'] = transcript['text'].apply(lambda x :" ".join([lem.lemmatize(word) for word in x.split()]))
transcript['text']

0       thank good afternoon everyone welcome nvidias ...
1       look past q1 expect channel inventory correcti...
3       china gaming weakness slower economic environm...
4       dont know could tear apart tease apart harlan ...
5         thank ill turn call back jenhsun closing remark
6       2018 record year disappointing finish quarter ...
8       addition announced record 40 plus new turing b...
9       also pleased see growing momentum rtx ecosyste...
10      pairing dl ray tracing provide comparable fram...
12      addition hyperscale cloud purchase declined se...
13      example recently announced rapid cuda accelera...
15      also strengthened product portfolio gotomarket...
16      moving pro visualization revenue reached 293 m...
17      webcast available replay conference call discu...
18      finally turning automotive q4 revenue 163 mill...
20      mercedesbenz also chosen nvidia next generatio...
21      moving rest pl balance sheet q4 gaap gross mar...
25      two question first colette talked weakness saw...
26      launched 2070 2080 first time weve ever launch...
27      think right box delivered excellent performanc...
31      slowdown broad based saw across every vertical...
35      fundamental gaming changed gamers ever game be...
36      take methodology colette described earlier ave...
42                              id like turn call colette
46      colette appreciate data gave u trying size nor...
47      ill start ill let jenhsun finish question alon...
48      think math isnt wrong part probably didnt cons...
50      thanks simona know lowered fourth quarter guid...
51      dont see high performance computing havent fou...
52      four new growth driver four new way grow data ...
                              ...
1592    second tax rate 2018 16 rate includes 487 mill...
1593    let turn result overall david mentioned enviro...
1594    overall performance 2018 demonstrates value di...
1595    turning page 6 individual segment investment b...
1596    moving underwriting market volatility declinin...
1597    investment banking franchise overall remains w...
1598    turning institutional client service page 7 ne...
1599    remaining decrease reflected lower result rate...
1601    first successfully increased wallet share 65 b...
1602    second remained focused leveraging bestinclass...
1603    lastly remained focused continued investment e...
1604    moving page 8 equity relates fourth quarter st...
1605    2018 equity produced net revenue 76 billion 15...
1606    moving equity investing lending page 9 equity ...
1607    moving debt investing lending page 10 fourth q...
1608    turning investment management page 11 business...
1609    let turn page 12 expense continued invest busi...
1610    let take component operating expense compensat...
1613    moving tax mentioned earlier tax rate 2018 16 ...
1614    turning page 13 capital common equity tier 1 r...
1615    full year repurchased 139 million share common...
1616    turning balance sheet liquidity page 14 global...
1617    taking question closing thought entered 2019 w...
1618    lastly management team motivated initial learn...
1628    together five name contributed 500 million rev...
1632    ill start glenn ill comment obviously weve bus...
1637    stephen maybe one il business obviously one th...
1639    sure thanks question think difficult give sens...
1640    thrown said comment 27 billion net interest in...
1642    okay followup expense side obviously 2018 thin...
Name: text, Length: 811, dtype: object

In [241]:
transcript['text'] = transcript['text'].apply(lambda x :" ".join([lem.lemmatize(word, pos='a') for word in x.split()]))
transcript['text'] = transcript['text'].apply(lambda x :" ".join([lem.lemmatize(word, pos='n') for word in x.split()]))
transcript['text'] = transcript['text'].apply(lambda x :" ".join([lem.lemmatize(word, pos='v') for word in x.split()]))
transcript['text'].head()

0    thank good afternoon everyone welcome nvidias ...
1    look past q1 expect channel inventory correcti...
3    china game weakness slow economic environment ...
4    dont know could tear apart tease apart harlan ...
5        thank ill turn call back jenhsun close remark
Name: text, dtype: object

In [242]:
transcript.head(15)

   sentiment                                               text
0   positive  thank good afternoon everyone welcome nvidias ...
1   positive  look past q1 expect channel inventory correcti...
3   negative  china game weakness slow economic environment ...
4   negative  dont know could tear apart tease apart harlan ...
5   positive      thank ill turn call back jenhsun close remark
6   negative  2018 record year disappoint finish quarter exp...
8   positive  addition announce record 40 plus new turing ba...
9   positive  also please see grow momentum rtx ecosystem ga...
10  positive  pair dl ray trace provide comparable frame rat...
12  negative  addition hyperscale cloud purchase decline seq...
13  positive  example recently announce rapid cuda accelerat...
15  positive  also strengthen product portfolio gotomarket c...
16  positive  move pro visualization revenue reach 293 milli...
17  positive  webcast available replay conference call discu...
18  positive  finally turn automotive q4 revenue 163 million...

In [243]:
transcript.to_csv('Earnings_Call_Transcript.csv')